version: '3.7'

services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: metrostreams
      POSTGRES_USER: rbeketov
      POSTGRES_PASSWORD: 12345
    ports:
      - 5436:5432
    volumes:
      - ./db/schema/:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

  redis:
    depends_on:
      - db
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
