# Generated by Django 4.2.5 on 2023-09-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsForModeling',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_application_create', models.DateField()),
                ('date_application_accept', models.DateField(blank=True, null=True)),
                ('date_application_complete', models.DateField(blank=True, null=True)),
                ('status_application', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applications_for_modeling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesOfModeling',
            fields=[
                ('modeling_id', models.AutoField(primary_key=True, serialize=False)),
                ('modeling_name', models.CharField(max_length=30)),
                ('modeling_description', models.CharField(max_length=1000)),
                ('modeling_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('modeling_image_url', models.CharField(max_length=40)),
                ('modeling_status', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'types_of_modeling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelingApplications',
            fields=[
                ('modeling', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.typesofmodeling')),
            ],
            options={
                'db_table': 'modeling_applications',
                'managed': False,
            },
        ),
    ]
